### ISSUE TITLE
Not an issue but WebDAV Idea

### ISSUE THREAD

**Issue by gashlin** [styletronix/cfapiSync#6]
So. Perhaps I am wrong but understanding how this all works and comparing it to other ideas out there. 

I think that if you want to incorporate WebDAV you may have to create a local DB index type. 
For instance. Would need to read all the files on the remote WebDAV and then create a local DB that processes them and turns them into files that contain all attributes except for the actual information that takes up space. Then on file attempting to be opened it would use a WebDAV client to download those files in the backend. 

Once again I am new at this so I am not sure since looking at other examples it does appear that it is reading a folder and watching it for changes which may be difficult to implement. 

So Client connects to WebDAV --> reads everything in all directories as reading creates a local DB.(XML) or JSON etc...
Then once that part is completed it goes back to the XML or JSON file and can see all attributes for all files that were in the connection. 

It then creates those files on the client machine wthout taking up space. 

Am I wrong?

**Comment by styletronix** [comment]
For this kind of implementation it may not be required to have an additional db because that informations could already stored in the placeholders. But watching for changes on the server is something else. For another project, i created a signalR Server which reports each change in the WebDav files to the client. But that's only working if you have full access to the WebDav server and can install something like SignalR or any other system for RealTime Messaging.
